/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class linkja_crypto_Library */

#ifndef _Included_linkja_crypto_Library
#define _Included_linkja_crypto_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     linkja_crypto_Library
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_linkja_crypto_Library_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
