/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_linkja_crypto_Library */

#ifndef _Included_org_linkja_crypto_Library
#define _Included_org_linkja_crypto_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_linkja_crypto_Library
 * Method:    getLibrarySignature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_linkja_crypto_Library_getLibrarySignature
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
